server:
  port: 8081

#中间件注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5  # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间
  client:
    service-url:
      defaultZone: http://wsb:wsb@localhost:8080/eureka/  #中间件注册中地址，默认使用用户名yw，密码yw进入
    registry-fetch-interval-seconds: 5

spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driverClassName: com.mysql.cj.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://10.1.32.69:3306/arrail-resource-server?useUnicode=true&characterEncoding=utf-8
    #username: root
    #password: 1qaz@WSX
    url: jdbc:mysql://10.1.33.126:3306/server1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    validationQuery: SELECT 1 FROM DUAL
  application:
    name: server1

#ribbon配置时长，处理超时
feign:
  hystrix:
    enabled: true

logging:
  level:
    com.app: debug

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml
tx-lcn: # 是否启动LCN负载均衡策略(优化选项，开启与否，功能不受影响)
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
  client: # 默认之配置为TM的本机默认端口
    manager-address: 127.0.0.1:8070